/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/users/kwangiit/slurm_4/lib/slurm";
char *default_slurm_config_file = "/users/kwangiit/slurm_4/etc/slurm.conf";
char *default_plugstack = "/users/kwangiit/slurm_4/etc/plugstack.conf";


/*char *default_plugin_path = "/usr/local/lib/slurm";
char *default_slurm_config_file = "/usr/local/etc/slurm.conf";
char *default_plugstack = "/usr/local/etc/plugstack.conf";*/
